name: firebase_chatapp
description: A multi-featured chat app using Flutter & Firebase.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # State management:
  provider: ^5.0.0

  # Local key-value storage:
  shared_preferences: ^2.0.5

  # Fonts & Animations:
  google_fonts: ^2.1.0
  animations: ^2.0.0

  # Form & Validation:
  flutter_form_builder: ^6.0.1

  # File & Image pickers:
  path_provider: ^2.0.1
  file_picker: ^3.0.1
  image_picker: ^0.7.5+2

  # Miscellaneous:
  mime: ^1.0.0
  open_file: ^3.2.1
  flutter_launcher_icons: ^0.9.0

  # Firebase auth:
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.3
  flutter_signin_button: ^2.0.0

  # Firebase firestore:
  cloud_firestore: ^2.2.0

  # Firebase cloud storage:
  firebase_storage: ^8.1.0

  # Firebase analytics:
  firebase_analytics: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3

flutter_icons:
  android: "launcher_icon"
  ios: true
#  image_path: "assets/icons/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
